name: pefish
auth:
  token1:
    shell:
      - whoami
      - pwd
      - "kubectl get *"
      - "kubectl describe pod *"
      - "kubectl logs *"
      - top
      - "tail *"
log-level: debug
server-token: test_token
server-address: 0.0.0.0:8181